import { Footer, Navbar } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";
import { StateContext } from "@/context/StateContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Crownn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StateContext>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          <div className="layout">
            <header>
              <Navbar />
            </header>
            <main className="main-container">{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
        </body>
      </html>
    </StateContext>
  );
}
